# Generated by Django 3.1 on 2020-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Avatar',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
