# Generated by Django 3.1 on 2020-08-25 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likes', models.BooleanField(default=False)),
                ('Unlikes', models.BooleanField(default=False)),
                ('Posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.posts')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
